version: "2"
checks:
  argument-count:
    enabled: false
  complex-logic:
    enabled: false
  method-lines:
    enabled: false
  file-lines:
    enabled: false
  method-complexity:
    enabled: false
  method-count:
    enabled: false
  nested-control-flow:
    enabled: false
  return-statements:
    config:
      threshold: 6
  similar-code:
    enabled: true
  identical-code:
    enabled: true
plugins:
  duplication:
    enabled: true
    config:
      languages:
        javascript:
          mass_threshold: 75
  eslint:
    enabled: true
    channel: "eslint-7"
  fixme:
    enabled: true
    config:
      strings:
        - FIXME
        - BUG
        - TODO
        - todo
        - console.log
  nodesecurity:
    enabled: true
  markdownlint:
    enabled: false
  csslint:
    enabled: true
  stylelint:
    enabled: true
  coffeelint:
    enabled: false
  sass-lint:
    enabled: false
exclude_patterns:
  - node_modules/
  - "test/"
  - "**/__tests__/"
  - "**/tests/**/*"
  - "package.json"
  - "**.min.*"
  - "public"
  - "static"
