# BUILD Settings:
# ##############################################################################
[build]
  publish = "public"

[dev]
  publish = "public"
  port = 64946
  autolaunch = true

# HEADERS - BASIC AUTH
# ##############################################################################
[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Content-Security-Policy = "default-src https: 'unsafe-inline' 'unsafe-eval'; form-action https:; img-src https: data:"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Strict-Transport-Security = "max-age=31536000"
    Permissions-Policy = "vibrate=(), geolocation=(), midi=(), notifications=(), push=(), microphone=(), camera=(), magnetometer=(), gyroscope=(), speaker=()"
    X-Frame-Options = "DENY"
[[headers]]
  for = "/editor"
  [headers.values]
    X-Frame-Options = "ALLOWALL"
[[headers]]
  for = "/user-guide/*"
  [headers.values]
    Basic-Auth = "saa:@lumn1@ss0c1@t10n"
    X-Robots-Tag = "noindex, nofollow"

# REDIRECTS
# ##############################################################################
#
# More redirects can be found in static/_redirects
#

# EDGE FUNCTIONS
# ##############################################################################

# Protected pages can redirect at the edge to the login page.
[[edge_functions]]
  path = "/travel-study/custom-journeys/request"
  function = "protected-content"

[[edge_functions]]
  path = "/travel-study/destinations/*/reserve"
  function = "protected-content"

[[edge_functions]]
  path = "/travel-study/destinations/*/notify"
  function = "protected-content"

[[edge_functions]]
  path = "/membership/join"
  function = "protected-content"

# PLUGINS
# ##############################################################################

# Fetch vault plugin needs to come before any of the contextual environment
# variable plugins so they can act on the new vars.
[[plugins]]
  package = "netlify-plugin-vault-variables"
  [plugins.inputs]
    endpoint = 'https://vault.stanford.edu'
    # Order doesn't matter here as these will be fetched asyncronously.
    # Try not to have dupes.
    secrets = ['secret/data/projects/adapt/saml', 'secret/data/projects/adapt/alumni']
    # Set which environment variables to use for the approle login
    secretId = 'VAULT_SECRET_ID'
    roleId = 'VAULT_ROLE_ID'

[[plugins]]
  package = '/plugins/netlify-plugin-contextual-auth'
  [plugins.inputs]
    username = 'adapt'
    password = 'letmein2021'
    context = ['branch-deploy', 'preview-build']

[[plugins]]
  package = "@netlify/plugin-gatsby"

# CONTEXTUAL PLUGINS
# ##############################################################################
[[context.production.plugins]]
  package = "netlify-plugin-submit-sitemap"
  [context.production.plugins.inputs]
    # Path to the sitemap URL (optional, default = /sitemap.xml)
    sitemapPath = "/sitemap/sitemap-index.xml"
