name: Merge to events-discovery

# Controls when the action will run.
on:
  pull_request:
    types: [ closed ]
    branches: [ dev ]

jobs:
  merge-to-events-discovery:
    name: Merge to events-discovery
    timeout-minutes: 10
    runs-on: ubuntu-latest
    # Only run on merged PRs.
    if: ${{ github.event.pull_request.merged }}

    steps:
      - name: Merge dev into events-discovery
        uses: devmasx/merge-branch@v1.3.1
        with:
          type: now
          from_branch: dev
          target_branch: events-discovery
          github_token: ${{ secrets.ADMIN_GITHUB_TOKEN }}
